table ANO-SAFRA
	lineageTag: 009602e1-d845-44b6-9dc4-02f710461faa

	measure _m-SEMANA-DA-ATUALIZACAO = ```
			
			VAR DataRef = MAX('ULTIMA-ATUALIZACAO'[SYSTIMESTAMP])
			RETURN
			CALCULATE (
			    MAX('ANO-SAFRA'[SEMANA-ATUAL]),
			    FILTER (
			        'ANO-SAFRA',
			        DataRef >= 'ANO-SAFRA'[DATA-INICIO]
			        && DataRef <= 'ANO-SAFRA'[DATA-FIM]
			    )
			)
			
			```
		lineageTag: 0c2422cd-82a9-408d-a67d-a4bcef262192

	column Value
		formatString: 0
		lineageTag: 7e2f086b-d871-4c43-a1ad-37798c079dc3
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	column Semana
		formatString: 0
		lineageTag: 9c7d84e9-feb5-4ab8-89d6-be0d864f698a
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Semana]

		annotation SummarizationSetBy = Automatic

	column DATA-INICIO
		formatString: Short Date
		lineageTag: e5919063-4582-4c44-a440-edf3bba3b3ac
		summarizeBy: none
		sourceColumn: [Data Início]

		annotation SummarizationSetBy = Automatic

	column DATA-FIM
		formatString: Short Date
		lineageTag: 5153c6e8-fdc7-46c3-a57a-c2320067b97a
		summarizeBy: none
		sourceColumn: [Data Fim]

		annotation SummarizationSetBy = Automatic

	column SEMANA-ATUAL
		lineageTag: 1761895f-6f1d-4923-9963-6be932d179cb
		summarizeBy: none
		sourceColumn: [Semana Atual]

		annotation SummarizationSetBy = Automatic

	partition ANO-SAFRA = calculated
		mode: import
		source = ```
				
				VAR StartDate = DATE(2025, 3, 31)  -- Segunda-feira da Semana 1
				VAR NumWeeks = 39
				RETURN
				ADDCOLUMNS (
				    GENERATESERIES(1, NumWeeks, 1),
				    "Semana", [Value],
				    "Data Início", StartDate + ([Value] - 1) * 7,
				    "Data Fim", StartDate + ([Value] - 1) * 7 + 6,
				    "Semana Atual", "2025-" & FORMAT([Value], "00")
				)
				
				```

	annotation PBI_Id = b79ae36c2f91427ba5338746037dd8e3

