table NOVOS-CDC
	lineageTag: 923f535b-f482-47b3-a0ff-53879f59dfb9

	column 'ID CC SAP'
		dataType: int64
		formatString: 0
		lineageTag: 4043c4d0-0ddc-4a2b-9649-4a1bb5094e1f
		summarizeBy: sum
		sourceColumn: ID CC SAP

		annotation SummarizationSetBy = Automatic

	column 'DESCRICAO CC SAP'
		dataType: string
		lineageTag: dabfa6fc-bd35-4754-916d-b3472d1fd8b8
		summarizeBy: none
		sourceColumn: DESCRICAO CC SAP

		annotation SummarizationSetBy = Automatic

	column 'ID | DESCRICAO CC SAP'
		dataType: string
		lineageTag: d15c3988-019a-486a-ac3f-fb70697dd355
		summarizeBy: none
		sourceColumn: ID | DESCRICAO CC SAP

		annotation SummarizationSetBy = Automatic

	column DEPARTAMENTO
		dataType: string
		lineageTag: 28abc113-9e1d-4bec-bea6-19dce2f75541
		summarizeBy: none
		sourceColumn: DEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	column 'ID | DESCRIÇÃO HIERARQUIA'
		dataType: string
		lineageTag: 885cb544-f871-419f-bcc7-a7a5daf29fee
		summarizeBy: none
		sourceColumn: ID | DESCRIÇÃO HIERARQUIA

		annotation SummarizationSetBy = Automatic

	column 'UND CMAA'
		dataType: string
		lineageTag: 36c11656-7707-4316-8094-3d3a54fa036f
		summarizeBy: none
		sourceColumn: UND CMAA

		annotation SummarizationSetBy = Automatic

	column 'ID CC ORACLE2'
		dataType: int64
		formatString: 0
		lineageTag: 69983f9b-e323-484b-a694-b67797b9b21b
		summarizeBy: sum
		sourceColumn: ID CC ORACLE2

		annotation SummarizationSetBy = Automatic

	column 'DESCRICAO CC ORACLE3'
		dataType: string
		lineageTag: 8c64faaa-d224-41f9-b4c0-0c8887790315
		summarizeBy: none
		sourceColumn: DESCRICAO CC ORACLE3

		annotation SummarizationSetBy = Automatic

	column 'ID | DESRICAO CC ORACLE4'
		dataType: string
		lineageTag: fab9f39a-57ff-4ef3-9d35-e6d7a4142a7d
		summarizeBy: none
		sourceColumn: ID | DESRICAO CC ORACLE4

		annotation SummarizationSetBy = Automatic

	partition NOVOS-CDC = m
		mode: import
		queryGroup: 'TABELA DE PARA'
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("5ZvLcuM2FoZfReV1UmMdHLu7lzTFdjOli0cXVyqpvMksJjOLrqyzy+OM32SeZACQPwhRJHGlpe7ZdByeH8APEMRFX51ff71bLu+X4l7+c/fD3areV8fdvi4W9XZ1OhzlX2v52EgW/1iMSOT/yH+FlhSrTb2tZah4+/r279258PR61ML7x/H2VHSsqd9+6CyT1HaNlcVu2DadebqQhVtfnrU7oFSa6drsbghZ4rnaV9uyLjbV9rhbvOx3P8muHxY/Lqrt86LevKyL7VFZt7olZAsBxYK7KT5c+FpVvTaq7ZdCv6C2KV1dW/rCnmdpe2h4ami2u1f5XzywRoanRuaiVPDA8KWr865dNKHKOIajV8YehAdZgxqg6qe2ZLUod9vjfreuFptiezoOT/sH2WJAseBhIJrwtSqaNqptNyWIJhz1C9gDoJaKz9V+r0upGWP1Ui0U/VhwV5b3Ay2oxxeV27bU91G8yFe6qn+pDl3Nljv1EYxIQk22y11X2Y9K9vYX6hPtQjcisI1/lPKyUgMvFcfqeV+smr/W9bOeoMMT6qOsPqBY+HelJnpZ1/Xiv//8M6QlVVR5Cy5qD8qnidk8OByfJmZz4kA8+npRWj8bXVdJ719PhSxTFt2ySdqf9Ri21awyNcoFanWa2hsJdb99LQ7tI9SrH9lGlHhdPO32hdrn5TJdHm1DquBAOMrYkru23v60alOhrh0rZBsVPaONBRPt+WyicTZF32bvfS9F3+zIS242qcOx0DvN30/Ful4Vq8qy3WxJQ4oo64LaFpWiV6GKtq1dRDvTQs/MdhtQ57RNVRbbuuxW1OYjGlbAtOgUUwP9sWuqkcmq3v7V1qXi/Wq6uO2Yzh1X60q2dOaYzh1bikDHH/qOq/XbH7quv9VbKT/pXarbb5cf+vVOFLD7xOd9Kov1qqr3Zxuv0LNnVBTYs4d+z85rU4p+RbbC9v7Q816/1mvL9UPPdRsO9Pt44betR8UunOpY55H1LK+3n/fFolJv4XiSf70Ux1oeAKtF8Vpt5YfRrYOs57yPHr1gfQ7Y9RcPY5+G2n/7/bJCpR1q+1Jrd09Vf6iepVKOsRRtqlVd1ttiIXdiufHJreDL+QrK+hvxLOLZSbHULg6bY3MOstdQsdTNXcTsTohu+Sw2T7X6UNY906JbP/sSX5NoRc2Tfh0qbK2Z52Hbqvpcy93mpNam9nZruWS9hvejngZZWHWbL6INWRV3IduY+haL9Wb3s/xKPzfnsItzFOtPclzlZ7S5RI/XIprr8pjAmF42l/t9VVYvZbMvyv3FLHvL5l4/EG5t6htD9bM53qlVameNJzFqb+JdBSqGqs9jtjl95dpXL8V+yJu+X11Efa2JwbpVYKBa25QqqCs2Q9LUbOJouBf3NLZUJ/PNTt5qikW7G6ijt3nSWWl+xJIVHbsr9rmZ5jesYQXsjCvMUH0cbkZ/DptWMlxLK7E9k54Sh3p12lk3xPpgmSY9MwYlAa4fxhtS0bE2Oq/NzeFz8aSOEKqJojyVxd4Yba4QQ3G4pC5uJrn6669GZm4RH3U7//m9q+nta1uViupaBqKd1eYoKe/u+ohj/XC2bI6Q5xHYEwP2qmOx3Z1dcT5ZNXenLX0fPH9s21FveSWX8nqtf/L6Uq/Uy1rZvtTgjEjCDD6Mt6WiY83YdvViUG3VCUt+aeuqPEn1Qh61V3vbsl4axmVBtmk53aZSTDXX2W9OWDghdh9Sc5Kyn8OgWnpPckT0jeRgj6WwalroekWzotkP7ab16Ufe8KuNnpqfT+qHh43lQZ91hgROM/Q4VreKDVdrWxN6IX2tMfOV7ql4LsqdZU8fgcdEbov3dhvmZasK3r62b/HebuFCYhtWu6U6YCkb54tb8XxS58Tq8Lw72u6VMb8S7lev7ltylrb/oyo+2rvNg54Nz5XZ1+TE3D93dyQlaH70vRSg8YdW0H0VRmK2P7TSXuHkVvmy2x+HiijxWYXj4q4bj/1FfV29Vit5Ejf9eOwv65YCHXkc+MItmTlP0mhbKjjSDMzyQ8te9pvil2prvVt7H9IqddgbVck9WP4rdVC9/bHt3jzf63l3WdxsQUox2EBvG1JOaKgqs/YZ1VB1RuX0+2A1Ij/6s8LcrPjD4dYpuwEg5wKA7e8rifyP/fgf5+R/cJ4P/3Ec/uM58V/byyvTP46ifzwj/WvH5R3hH8fBP54T/rWj8C7sjyfYHyezP/zOG4r+2I3+OBf6KwH27tLJH8eRP56T/OGbuhb441Dwx/OAP4zDfNyPh7kfp3I/7Im+2I+nsR/nwn74umOpH09SP85E/eAyB/RjJ/TjjNAPp4Q05sdO5sc5mJ9BenepyI+dyI9zID8Yeg/ixz7EjzMRP3QsD/DjaeDHycAPduN5HwfyPs7I++B+PtzH4biP8+I+rEPxtI/dtI/TaB88psI+noR9HA37cPqIZX3sxfo4mfXhNJwD9fE06uN41IcbUjzp40nSx9GkD85iQB87QB8ngD6sU36cj52cj1M5HwYqF+ZjN+bjZMwH02mUjx2UjzNQPtwZ0iAfj0I+ToB88BbK+NjN+DgH44O/NMTHfoiPcyE+zM08hI9HCB8HET6MZAjgYxfg4zjAh/GJ53vsw/c4nu/BYS68x8F4jzPhPbz3KbrHLrrHqXQPe96ccI+dcI+zwD2cH1PYHnuxPY5ne9pkNrTHXmiP49Ee7KaRPXKn9kGSgeydXl/uktEe+aX2QZYJ7RnrudgexaX2odhMbA/dvCrco6jUPpSaB+5hYN6N7lFcah+KzUT3MAzvgPdoIrUPsRS8h64E8j1yp/ZBkoHvtSZzAD6KS+1DsZkAn/murkP4KDS1DwWyEz4zEHMhPhpO7cPjBMRn9kY/xkfTqX0IZ2B85hOPg3w0mdqHaDrkMzbTKR85U/ugyEP5zHkhBfORM7UPikTMZwY6lfORM7UPikTOZxzPD/rIJ7UPonTQZ3qWg/TRdGofwimkz/iNRX0UmNoHfR7UZ+zPxfooPLUPRbKxPrMaxcI+cqf2QRIN+4zJNNpHk6l9iMbQPnMSicN95JXaB1UK7jOH43TeR9OpfQhH8T5zZ4oFfjSZ2odoDPAz1sKJHzlS+xCPI35mufJBfuRM7YMiAfmZocrD/Mid2gdJCvMzrlOgHzlS+xBPg37mFpFC/Wg0tQ+ROOpnzIVhP3Kn9kGSiP2MwRTuR36pfZBl4H5mfuYAfzSS2ofnvuDPjKU/+SNXah8EweTPjFAs+iOf1D6IotCfsZiH/VFwah9KpLM/8+rH4R+5UvsgSIB/Zvubj/6RM7UPilT6Z86T8fiPvFL7KC21T7nMxP/IK7WP0lL7Wr+pAJDcAJBuDACSHwCkGweAFAcA6f8AAFIUAKTvCwBSHACk7wYA0gQApOsBQHIDQLpJAEhxAJC+awBIoQCQvlkASMMAkN4dANI0AKSbAYA0CQDpFgEgOQEg3R4AJCcApBsDgOQEgPTNAUDyAYB0mwCQpgEg3QIApEAASN8WAKRwAEg3BwDJDQDpRgAgTQJAuh4AJC8ASLcFAGkaANJVASBNAkC6DgAkBwCk9wOA5ASAdHMAkNwAkG4FAJIDANLtAEAaBYB0DQBIbgBINwQAyQ8A0o0CQBoBgDQ/ACQXAKSrAUDyAYB0QwCQggEgvScAJBcApG8CAJITANLtAEDyAoB0MwCQvAAgXR0ACncGICQ5AGCZAQAKvwxAyHIBQFjPBQBFXAYgis0FAMsbAIAiKgMQpWYCgOU7A0ARlwGIYnMBwPLdAKCYyABELAkAllEAULgzACHJAQDLbABQxGUAothcABDf1XUAoAjNAESB/AAQAzEXABTDGYB4nAIAsTf6AUAxnQGIcA4AiE88DgCKyQxARDMAQNhMB4DCmQEIRSYAiPNCCgAUzgxAKFIBIAY6FQAKZwYgFKkAEI7nB4DCJwMQogwAED3LAQDFdAYgwkkAEH5jAaAIzACEPhMAhP25AKAIzwBEkXwAEKtRLAAU7gxASOIBIEymAUAxmQGIaBQAxEkkDgAKrwxAqJIAIA7H6QBQTGcAIhwHAHFnigWAYjIDENEoAAhr4QBQODIAEY8EgFiufACgcGYAQpECADFUeQCgcGcAQpIEAOE6BQAKRwYg4okAELeIFAAoRjMAEYkEgDAXBgCFOwMQklQACIMpAFD4ZQBClgMAYn7mAIBiJAMQz70BIMbSHwAKVwYgBOEAECMUCwCFTwYgRHEAEBbzAEARnAGIEhkAIF79OAAUrgxACFIAILa/+QCgcGYAQpEMAHGejAeAwisDUCRlAJYZAaDwygAUSRmA8BsPAH/7Hw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"ID CC SAP" = _t, #"DESCRICAO CC SAP" = _t, #"ID | DESCRICAO CC SAP" = _t, DEPARTAMENTO = _t, #"ID | DESCRIÇÃO HIERARQUIA" = _t, #"UND CMAA" = _t, #"ID CC ORACLE2" = _t, #"DESCRICAO CC ORACLE3" = _t, #"ID | DESRICAO CC ORACLE4" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"ID CC SAP", Int64.Type}, {"DESCRICAO CC SAP", type text}, {"ID | DESCRICAO CC SAP", type text}, {"DEPARTAMENTO", type text}, {"ID | DESCRIÇÃO HIERARQUIA", type text}, {"UND CMAA", type text}, {"ID CC ORACLE2", Int64.Type}, {"DESCRICAO CC ORACLE3", type text}, {"ID | DESRICAO CC ORACLE4", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

