table PCP-DADOS-VERSO-CARTILHA
	lineageTag: 3e2f9db5-f383-4be8-bfa2-11b77f84868d

	measure _m-SEMANA-DADOS-CARTILHA =
			
			VAR DataRef = MAX('PCP-DADOS-VERSO-CARTILHA'[DATA])
			RETURN
			CALCULATE (
			    MAX('ANO-SAFRA'[SEMANA-ATUAL]),
			    FILTER (
			        'ANO-SAFRA',
			        DataRef >= 'ANO-SAFRA'[DATA-INICIO]
			        && DataRef <= 'ANO-SAFRA'[DATA-FIM]
			    )
			)
		lineageTag: ba93af03-fa6f-44b4-89ae-a4d46989a674

	column EMPRESA
		dataType: string
		lineageTag: d6eb8c44-daac-4819-a4b3-0594b78cb171
		summarizeBy: none
		sourceColumn: EMPRESA

		annotation SummarizationSetBy = Automatic

	column DATA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2caeacd3-158b-4fe5-b962-1df83545b229
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column VAR_CODIGO
		dataType: string
		lineageTag: 903e6df7-d678-41c4-8bfe-85ea000e61fa
		summarizeBy: none
		sourceColumn: VAR_CODIGO

		annotation SummarizationSetBy = Automatic

	column VAR_DESCRI
		dataType: string
		lineageTag: d010f1e4-b406-4c0a-9a70-485b6b0243ba
		summarizeBy: none
		sourceColumn: VAR_DESCRI

		annotation SummarizationSetBy = Automatic

	column LAN_VALOR_A
		dataType: decimal
		formatString: #,0.00
		lineageTag: f9f8fbb9-6de1-4fda-be7a-9b4aadd05461
		summarizeBy: sum
		sourceColumn: LAN_VALOR_A

		annotation SummarizationSetBy = Automatic

	partition PCP-DADOS-VERSO-CARTILHA = m
		mode: import
		queryGroup: 'PILAR IPM'
		source =
				let
				    Fonte = Oracle.Database("ppim", [HierarchicalNavigation=true, Query="    select #(lf)        decode(emp_codemp, '001','UVT', '002','UVP', '003','UCP') empresa,#(lf)        bdata,#(lf)        var_codigo,#(lf)        var_descri,#(lf)        lan_valor_a#(lf)        #(lf)    from pims_pi.proboletim#(lf)    #(lf)    where emp_codemp in ('001')#(lf)    #(lf)        and var_codigo in (#(lf)                           'PRODACUTON',#(lf)                           '0CANAMOIDA',#(lf)                           'EFICGLOBAL'#(lf)                          )#(lf)    group by#(lf)        emp_codemp,#(lf)        bdata,#(lf)        var_codigo,#(lf)        var_descri,#(lf)        lan_valor,#(lf)        lan_valor_s,#(lf)        lan_valor_m,#(lf)        lan_valor_a#(lf)        #(lf)    union all#(lf)    #(lf)    -- script acumulado UVP#(lf)    select #(lf)        decode(emp_codemp, '001','UVT', '002','UVP', '003','UCP') empresa,#(lf)        bdata,#(lf)        var_codigo,#(lf)        var_descri,#(lf)        lan_valor_a#(lf)        #(lf)    from pims_pi.proboletim#(lf)    #(lf)    where emp_codemp in ('002')#(lf)    #(lf)        and var_codigo in (#(lf)                           'PRODACUTON',#(lf)                           '0CANAMOIDA',#(lf)                           'EFICGLOBAL'#(lf)                          )#(lf)    group by#(lf)        emp_codemp,#(lf)        bdata,#(lf)        var_codigo,#(lf)        var_descri,#(lf)        lan_valor,#(lf)        lan_valor_s,#(lf)        lan_valor_m,#(lf)        lan_valor_a#(lf)        #(lf)    union all#(lf)    #(lf)    -- script acumulado UVT#(lf)    select #(lf)        decode(emp_codemp, '001','UVT', '002','UVP', '003','UCP') empresa,#(lf)        bdata,#(lf)        var_codigo,#(lf)        var_descri,#(lf)        lan_valor_a#(lf)        #(lf)    from pims_pi.proboletim#(lf)    #(lf)    where emp_codemp in ('003')#(lf)    #(lf)        and var_codigo in (#(lf)                           'PRODACUTON',#(lf)                           '0CANAMOIDA',#(lf)                           'EFICGLOBAL'#(lf)                          )#(lf)    group by#(lf)        emp_codemp,#(lf)        bdata,#(lf)        var_codigo,#(lf)        var_descri,#(lf)        lan_valor,#(lf)        lan_valor_s,#(lf)        lan_valor_m,#(lf)        lan_valor_a#(lf)        #(lf)"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"BDATA", type date}}),
				    #"Linhas Classificadas" = Table.Sort(#"Tipo Alterado",{{"BDATA", Order.Descending}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Linhas Classificadas", each [BDATA] > #date(2025, 3, 31)),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Linhas Filtradas",{{"LAN_VALOR_A", Currency.Type}, {"BDATA", type date}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado1",{{"BDATA", "DATA"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

