table SOMA-TOTAL-PILAR-IPM
	lineageTag: a5ee9b3a-36d5-4109-8fc8-e3f1a7021e41

	measure _m-IPM-EXTRACAO = ```
			
			
			    VAR APROVIND = CALCULATE(
			
			        [_m-R$MaiorMelhorPcpAcumulado],
			        'AREAS-PRODUCAO'[Indicador] = "Aproveitamento de Tempo Industrial",
			        'AREAS-PRODUCAO'[Pilar] = "IPM",
			        'PCP-ACUMULADO'[VAR_CODIGO] = "00APROVIND"
			    )
			
			    VAR EXTRACAO = CALCULATE(
			
			        [_m-R$MaiorMelhorPcpAcumulado],
			        'AREAS-PRODUCAO'[Indicador] = "Extração ART",
			        'AREAS-PRODUCAO'[Pilar] = "IPM",
			        'PCP-ACUMULADO'[VAR_CODIGO] = "EXTRCANART"
			    )
			
			        VAR UMIDADE = CALCULATE(
			
			            [_m-R$MenorMelhorPcpAcumulado],
			            'AREAS-PRODUCAO'[Indicador] = "Umidade do Bagaço",
			            'AREAS-PRODUCAO'[Pilar] = "IPM",
			            'PCP-ACUMULADO'[VAR_CODIGO] = "0UMID_DESF"
			        )
			
			            VAR CHAPISCO = CALCULATE(
			
			                [_m-R$ValorEntre_A_&_B_PcpAcumulado],
			                'AREAS-PRODUCAO'[Indicador] = "Consumo de Chapisco",
			                'AREAS-PRODUCAO'[Pilar] = "IPM",
			                'PCP-ACUMULADO'[VAR_CODIGO] = "CONSELEARA"
			            )
			
			RETURN
			
			APROVIND +
			EXTRACAO +
			UMIDADE +
			CHAPISCO
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 62061502-9624-441e-9788-3737646d5a84

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure _m-IPM-UTILIDADES-UVT = ```
			
			
			    VAR APROVIND = 
			    
			        CALCULATE(
			
			            [_m-R$MaiorMelhorPcpAcumulado],
			            'AREAS-PRODUCAO'[Indicador] = "Aproveitamento de Tempo Industrial",
			            'AREAS-PRODUCAO'[Pilar] = "IPM",
			            'PCP-ACUMULADO'[VAR_CODIGO] = "00APROVIND"
			        )
			
			        VAR CONSH2OBRUTA =
			
			            CALCULATE(
			
			                [_m-R$MenorMelhorPcpAcumulado],
			                'AREAS-PRODUCAO'[Indicador] = "Consumo de Água Bruta",
			                'AREAS-PRODUCAO'[Pilar] = "IPM",
			                'PCP-ACUMULADO'[VAR_CODIGO] = "0AGBRUTATC"
			            )
			
			            VAR CTRLSILSAT = CALCULATE(
			
			                [_m-R$CartaoMenorMelhorProlancaXxx],
			                'PCP-PROLANCA'[100 SafraProlanca] = "2025/2026",
			                'AREAS-PRODUCAO'[Indicador] = "Controle de Sílica (Vapor Saturado)",
			                'AREAS-PRODUCAO'[Pilar] = "IPM",
			                'PCP-PROLANCA'[VAR_CODIGO] = "00MEDVPSAT",
			                'PCP-PROLANCA'[SUF_CODIGO] = "01"
			            )
			
			                VAR CTRLPH = CALCULATE(
			
			                    [_m-R$ValorEntre_A_&_B_ProlancaXxx],
			                    'AREAS-PRODUCAO'[Indicador] = "Controle pH (Alimentação Caldeira)",
			                    'PCP-PROLANCA'[100 SafraProlanca] = "2025/2026",
			                    'AREAS-PRODUCAO'[Pilar] = "IPM",
			                    'PCP-PROLANCA'[VAR_CODIGO] = "0000PH_ALI",
			                    'PCP-PROLANCA'[SUF_CODIGO] = "01"
			                )
			
			    var INDICADOR = CTRLPH + CTRLSILSAT + CONSH2OBRUTA + APROVIND
			RETURN
			
			INDICADOR
			
			```
		lineageTag: 5658ceb9-e0cb-416a-a0f8-aa920d065d0b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _m-IPM-FABRICA-ACUCAR-UVT = ```
			
			
			VAR CRISMASSAA = CALCULATE(
			
			    [_m-R$MaiorMelhorPcpAcumulado],
			    'AREAS-PRODUCAO'[Indicador] = "Rendimento de Cristais da Massa A",
			    'PCP-ACUMULADO'[VAR_CODIGO] = "CRISMASSAA"
			)
			
			VAR RECUPER = CALCULATE(
			
			    [_m-R$MaiorMelhorPcpAcumulado],
			    'AREAS-PRODUCAO'[Indicador] = "Recuperação de Fábrica (SJM)"
			    ,'PCP-ACUMULADO'[VAR_CODIGO] ="RECUPERFAB"
			)
			
			VAR PERDAS = CALCULATE(
			
			    [_m-R$MenorMelhorPcpAcumulado],
			    'AREAS-PRODUCAO'[Indicador] = "Perdas no Multijato",
			    'PCP-ACUMULADO'[VAR_CODIGO] ="0PPERDMULEV",
			    'AREAS-PRODUCAO'[Pilar]="IPM"
			)
			
			VAR COR = CALCULATE(
			
			    [_m-R$CartaoMenorMelhorProlancaXxx],
			    'AREAS-PRODUCAO'[Indicador] = "Cor do Açúcar",
			    'PCP-PROLANCA'[VAR_CODIGO] ="0CORACUCAR",
			    'PCP-PROLANCA'[100 SafraProlanca] = "2025/2026"
			)
			
			VAR INDICADOR = CRISMASSAA + RECUPER + PERDAS + COR
			RETURN
			
			INDICADOR
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 8cd4e019-4324-4424-8fce-2c02520f8897

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure _m-IPM-TRATAMENTO-CALDO = ```
			
			
			VAR TURBIDEZ = 
			    CALCULATE(
			        [_m-R$CartaoMenorMelhorProlancaXxx],
			        'AREAS-PRODUCAO'[Indicador] = "Controle de Turbidez (Saída Decantador Açúcar)",
			        'PCP-PROLANCA'[LAN_HORA] = "XXXX",
			        'AREAS-PRODUCAO'[Pilar] = "IPM",
			        'PCP-PROLANCA'[VAR_CODIGO] = "0TURBIDEZ",
			        'PCP-PROLANCA'[SUF_CODIGO] = "01",
			        'PCP-PROLANCA'[100 SafraProlanca] = "2025/2026"
			    )
			
			    VAR BRIX = 
			        CALCULATE(
			            [_m-R$CartaoMaiorMelhorProlancaXxx],
			            'AREAS-PRODUCAO'[Indicador] = "Brix do Xarope",
			            'PCP-PROLANCA'[LAN_HORA] = "XXXX",
			            'AREAS-PRODUCAO'[Pilar] = "IPM",
			            'PCP-PROLANCA'[VAR_CODIGO] = "000BXXAROP",
			            'PCP-PROLANCA'[SUF_CODIGO] = "01",
			            'PCP-PROLANCA'[100 SafraProlanca] = "2025/2026"        
			        )
			
			        VAR PH = 
			            CALCULATE(
			                [_m-R$ValorEntre_A_&_B_ProlancaXxx], 
			                'AREAS-PRODUCAO'[Indicador] = "Controle de p.H (Caldo Dosado)",
			                'AREAS-PRODUCAO'[Pilar] = "IPM",
			                'PCP-PROLANCA'[VAR_CODIGO] = "0CMISTOPHF",
			                'PCP-PROLANCA'[SUF_CODIGO] = "01",
			                'PCP-PROLANCA'[LAN_HORA] = "XXXX",
			                'PCP-PROLANCA'[100 SafraProlanca] = "2025/2026"
			            )
			
			            VAR POL = 
			                CALCULATE(
			                    [_m-R$MenorMelhorPcpAcumulado],
			                    'AREAS-PRODUCAO'[Pilar] = "IPM",
			                    'AREAS-PRODUCAO'[Indicador] = "Pol da Torta",
			                    'PCP-ACUMULADO'[VAR_CODIGO] = "0MEDPOLTOR"               
			                )
			VAR INDICADOR = POL +TURBIDEZ+PH+BRIX
			
			RETURN
			INDICADOR
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 82b66440-05fb-47cd-bd49-1247f7bd429d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure _m-IPM-FABRICA-ETANOL-UVT = ```
			
			
			
			VAR EFICFERM = 
			    CALCULATE(
			        [_m-R$MaiorMelhorPcpAcumulado],     
			        'AREAS-PRODUCAO'[Indicador] = "Eficiência Fermentação p/ Subprodutos",
			        'PCP-ACUMULADO'[VAR_CODIGO] = "000RENDFER"
			    )
			
			    VAR EFICDEST = 
			        CALCULATE(
			            [_m-R$MaiorMelhorPcpAcumulado],      
			            'AREAS-PRODUCAO'[Indicador] = "Eficiência Destilação",
			            'AREAS-PRODUCAO'[Pilar] = "IPM",
			            'PCP-ACUMULADO'[VAR_CODIGO] = "00RENDDEST"
			        )
			
			        VAR PH = 
			            CALCULATE(
			                [_m-R$ValorEntre_A_&_B_ProlancaXxx],
			                'AREAS-PRODUCAO'[Pilar] = "IPM",
			                'AREAS-PRODUCAO'[Indicador]= "Controle de pH (Etanol Hidratado)",
			                'PCP-PROLANCA'[VAR_CODIGO]="0PRODALCPH",
			                'PCP-PROLANCA'[LAN_HORA] = "XXXX",
			                'PCP-PROLANCA'[SUF_CODIGO]="01",
			                'PCP-PROLANCA'[100 SafraProlanca] = "2025/2026"
			            )
			
			            VAR ACIDO = 
			                CALCULATE(
			                    'AREAS-PRODUCAO'[_m-R$MenorMelhor],
			                    'AREAS-PRODUCAO'[Indicador] = "Consumo de Ácido Sulfúrico",
			                    'AREAS-PRODUCAO'[Pilar] = "IPM"
			            )
			
			RETURN
			
			EFICFERM +
			EFICDEST +
			PH +
			ACIDO 
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 3a6df275-57dd-4b64-b33f-10916278fdf7

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure _m-IPM-UTILIDADES-UVP = ```
			
			
			    VAR APROVIND = 
			        CALCULATE(
			            [_m-R$MaiorMelhorPcpAcumulado],
			            'AREAS-PRODUCAO'[Indicador] = "Aproveitamento de Tempo Industrial",
			            'PCP-ACUMULADO'[VAR_CODIGO] = "00APROVIND"
			        )
			        
			        VAR CONSAGUA = 
			            CALCULATE(
			                [_m-R$MenorMelhorPcpAcumulado],
			                'AREAS-PRODUCAO'[Indicador] = "Consumo de Água Bruta",
			                'AREAS-PRODUCAO'[Pilar] = "IPM",
			                'PCP-ACUMULADO'[VAR_CODIGO] = "0AGBRUTATC"
			            )
			            VAR SILSAT = 
			                CALCULATE(
			                    [_m-R$CartaoMenorMelhorProlancaXxx],
			                    'AREAS-PRODUCAO'[Indicador] = "Controle de Sílica (Vapor Saturado)",
			                    'PCP-PROLANCA'[VAR_CODIGO] ="000SIVAPOR",
			                    'PCP-PROLANCA'[SUF_CODIGO] = "01",
			                    'PCP-PROLANCA'[100 SafraProlanca] = "2025/2026"
			                )
			
			                VAR PH = 
			                    CALCULATE(
			                        [_m-R$ValorEntre_A_&_B_ProlancaXxx],
			                        'AREAS-PRODUCAO'[Indicador] = "Controle pH (Alimentação Caldeira)",
			                        'PCP-PROLANCA'[VAR_CODIGO] ="0000PH_ALI"
			                    )
			
			VAR INDICADORES = APROVIND + consagua + SILSAT + PH
			
			RETURN
			INDICADORES
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 73499a33-2a7e-43a2-8bb4-79994d5c5b59

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure _m-IPM-TRATAMENTO-CALDO-UVP = ```
			
			
			 
			VAR TURBIDEZ = 
			    CALCULATE(
			        [_m-R$CartaoMenorMelhorProlancaXxx],
			        'AREAS-PRODUCAO'[Indicador] = "Controle de Turbidez (Saída Decantador Açúcar)",
			        'AREAS-PRODUCAO'[Pilar] = "IPM",
			        'PCP-PROLANCA'[VAR_CODIGO] = "00TURBIDEZ",
			        'PCP-PROLANCA'[SUF_CODIGO] = "02",
			        'PCP-PROLANCA'[LAN_HORA] = "XXXX",
			        'PCP-PROLANCA'[100 SafraProlanca] = "2025/2026"
			    )
			
			    VAR BRIX = 
			        CALCULATE(
			            [_m-R$ValorEntre_A_&_B_ProlancaXxx],  
			            'AREAS-PRODUCAO'[Indicador]= "Brix do Xarope",
			            'AREAS-PRODUCAO'[Pilar] = "IPM",
			            'PCP-PROLANCA'[VAR_CODIGO] = "000BXXAROP",
			            'PCP-PROLANCA'[LAN_HORA] = "XXXX",
			            'PCP-PROLANCA'[SUF_CODIGO] = "01",
			            'PCP-PROLANCA'[100 SafraProlanca] = "2025/2026"
			        )
			
			        VAR PH = 
			            CALCULATE(
			                [_m-R$ValorEntre_A_&_B_ProlancaXxx], 
			                'AREAS-PRODUCAO'[Indicador]="Controle de p.H (Caldo Dosado)",
			                'AREAS-PRODUCAO'[Pilar] = "IPM",
			                'PCP-PROLANCA'[VAR_CODIGO] = "0CMISTOPHF",
			                'PCP-PROLANCA'[SUF_CODIGO] = "01",
			                'PCP-PROLANCA'[LAN_HORA] = "XXXX",
			                'PCP-PROLANCA'[100 SafraProlanca] = "2025/2026"
			            )
			
			            VAR PERDA = 
			                CALCULATE(
			                    [_m-R$MenorMelhorPcpAcumulado],
			                    'AREAS-PRODUCAO'[Indicador]="Perdas no Multijato",
			                    'AREAS-PRODUCAO'[Pilar] = "IPM",
			                    'PCP-ACUMULADO'[VAR_CODIGO]="PPERDMULEV"
			                )
			
			RETURN
			
			TURBIDEZ +
			BRIX+
			PH 
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 45caa81d-6ece-4158-b850-959e1f9ba658

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure _m-IPM-FABRICA-ETANOL-UVP = ```
			
			
			
			VAR EFICFERM = 
			    CALCULATE(
			        [_m-R$MaiorMelhorPcpAcumulado],     
			        'AREAS-PRODUCAO'[Indicador] = "Eficiência Fermentação p/ Subprodutos",
			        'PCP-ACUMULADO'[VAR_CODIGO] = "00000EFCTC"
			    )
			
			    VAR EFICDEST = 
			        CALCULATE(
			            [_m-R$MaiorMelhorPcpAcumulado],      
			            'AREAS-PRODUCAO'[Indicador] = "Eficiência Destilação",
			            'PCP-ACUMULADO'[VAR_CODIGO] = "00RENDDEST"
			        )
			
			        VAR PH = 
			            CALCULATE(
			                [_m-R$ValorEntre_A_&_B_ProlancaXxx],
			                'AREAS-PRODUCAO'[Indicador]= "Controle de pH (Etanol Hidratado)",
			                'PCP-PROLANCA'[VAR_CODIGO]="0PRODALCPH",
			                'PCP-PROLANCA'[SUF_CODIGO]="01"
			            )
			
			            VAR ACIDO = 
			                CALCULATE(
			                    [_m-R$MenorMelhor],   
			                    'AREAS-PRODUCAO'[Indicador]="Consumo de Ácido Sulfúrico"
			            )
			
			RETURN
			
			EFICFERM +
			EFICDEST +
			PH +
			ACIDO 
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 5b6830c4-5383-49e8-9744-46511146ed9b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure _m-IPM-UTILIDADES-UCP = ```
			
			
			    VAR APROVIND = 
			        CALCULATE(
			            [_m-R$MaiorMelhorPcpAcumulado],
			            'AREAS-PRODUCAO'[Indicador]= "Aproveitamento de Tempo Industrial",
			            'PCP-ACUMULADO'[VAR_CODIGO]="00APROVIND"
			        )
			        
			        VAR CONSAGUA = 
			        CALCULATE(
			            [_m-R$MenorMelhorPcpAcumulado],
			            'AREAS-PRODUCAO'[Indicador]= "Consumo de Água Bruta",
			            'AREAS-PRODUCAO'[Pilar] = "IPM",
			            'PCP-ACUMULADO'[VAR_CODIGO]="0AGBRUTATC"
			        )
			
			        VAR SILSAT = 
			            CALCULATE(
			                [_m-R$MaiorMelhorPcpAcumulado],
			                'AREAS-PRODUCAO'[Indicador]= "Controle de Sílica (Água concentração das caldeiras)",
			                'PCP-PROLANCA'[VAR_CODIGO]="00MEDSICAL",
			                'AREAS-PRODUCAO'[Pilar] = "IPM"
			            )
			
			            VAR PH = 
			                CALCULATE(
			                    [_m-R$ValorEntre_A_&_B_ProlancaXxx],
			                    'AREAS-PRODUCAO'[Indicador] = "Controle pH (Alimentação Caldeira)",
			                    'PCP-PROLANCA'[VAR_CODIGO]="0000PH_ALI",
			                    'AREAS-PRODUCAO'[Pilar] = "IPM",
			                    'PCP-PROLANCA'[SUF_CODIGO] = "01",
			                    'PCP-PROLANCA'[100 SafraProlanca] = "2025/2026"
			                )
			VAR INDICADORES = APROVIND + SILSAT +CONSAGUA+ PH
			RETURN
			
			INDICADORES
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: cc665e66-bf6f-41b7-9112-c6f9ff3c5015

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure _m-IPM-FABRICA-ACUCAR-UCP =
			
			
			VAR CRISMASSAA = CALCULATE(
			
			    [_m-R$MaiorMelhorPcpAcumulado],
			    'AREAS-PRODUCAO'[Indicador]= "Rendimento de Cristais da Massa A",
			    'AREAS-PRODUCAO'[Pilar] = "IPM",
			    'PCP-ACUMULADO'[VAR_CODIGO]="CRISMASSAA"
			)
			
			VAR SACASACUCAR = CALCULATE(
			
			    [_m-R$MaiorMelhorSacasAcucarTonCana],
			    'AREAS-PRODUCAO'[Indicador] = "Sacas de açucar p/ Ton Cana",
			    'AREAS-PRODUCAO'[Pilar] = "IPM"
			
			)
			
			VAR PERDAS = CALCULATE(
			
			    [_m-R$MenorMelhorPcpAcumulado],
			    'AREAS-PRODUCAO'[Indicador]= "Perdas no Multijato",
			    'PCP-ACUMULADO'[VAR_CODIGO]="PPERDMULEV",
			    'AREAS-PRODUCAO'[Pilar] = "IPM"
			)
			
			VAR COR = CALCULATE(
			
			    [_m-R$CartaoMenorMelhorProlancaXxx],
			    'AREAS-PRODUCAO'[Indicador] = "Cor do Açúcar",
			    'AREAS-PRODUCAO'[Pilar] = "IPM",
			    'PCP-PROLANCA'[VAR_CODIGO] = "0CORACUCAR",
			    'PCP-PROLANCA'[100 SafraProlanca] = "2025/2026"
			)
			
			
			RETURN
			
			CRISMASSAA +
			SACASACUCAR +
			PERDAS +
			COR
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 79cb7fca-75ad-4116-9686-b7d114bc9990

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure _m-IPM-OFICINAS-MANUTENCAO = ```
			
			
			    VAR APROVIND = 
			        CALCULATE(
			            [_m-R$MaiorMelhorPcpAcumulado],
			            'AREAS-PRODUCAO'[Indicador] = "Aproveitamento de Tempo Industrial",
			            'AREAS-PRODUCAO'[Pilar] = "IPM",
			            'PCP-ACUMULADO'[VAR_CODIGO] = "00APROVIND"
			        )   
			
			        VAR BACKLOG = 
			            CALCULATE(
			                [_m-R$ValorEntre_A_&_B],
			                'AREAS-PRODUCAO'[Indicador] = "Backlog de Execução",
			                'AREAS-PRODUCAO'[Pilar] = "IPM"
			            )
			
			            VAR ADERENCIA_OS = 
			                CALCULATE(
			                    [_m-R$MaiorMelhor],
			                    'AREAS-PRODUCAO'[Indicador] = "Aderência ao Inicio de Execução de O.S Programada",
			                    'AREAS-PRODUCAO'[Pilar] = "IPM"
			                )
			
			                VAR HRS_REALZ_CORR = 
			                    CALCULATE(
			                        [_m-R$MenorMelhor],
			                        'AREAS-PRODUCAO'[Indicador] = "Índice Horas Realizadas Corretivas  (Fora programação)",
			                        'AREAS-PRODUCAO'[Pilar] = "IPM"
			                    )
			
			                    VAR HRS_PROD = 
			                        CALCULATE(
			                            [_m-R$MaiorMelhor],
			                            'AREAS-PRODUCAO'[Indicador] = "Horas Produtivas  (Apontamento de Mão de Obra)",
			                            'AREAS-PRODUCAO'[Pilar] = "IPM"
			                        )
			
			// ----------- > SOMA VARIÁVEIS
			VAR INDICADOR = APROVIND +BACKLOG+ ADERENCIA_OS + HRS_REALZ_CORR + HRS_PROD
			RETURN
			INDICADOR         
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: b07dce69-3a27-444d-8ce8-bce9eafaaf17

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure _m-AREAS-APOIO-ARMAZEM-ACUCAR-UVT = ```
			
			
			
			VAR APROV_IND = 
			    CALCULATE(
			        [_m-R$MaiorMelhorPcpAreasApoio],     
			        'AREAS-APOIO'[PILAR] = "Aproveitamento de Tempo Industrial",
			        'PCP-ACUMULADO'[VAR_CODIGO] = "00APROVIND"
			    )
			
			        VAR DEV_ACUCAR = 
			            CALCULATE(
			                [_m-R$MenorMelhorPcpAreasApoio],      
			                'AREAS-APOIO'[PILAR] = "Devolução de Açúcar",
			                'PCP-ACUMULADO'[VAR_CODIGO] = "0DEVPROCAC"
			            )
			
			                VAR DEV_ETANOL = 
			                    CALCULATE(
			                    [_m-R$MenorMelhorPcpAreasApoio],      
			                    'AREAS-APOIO'[PILAR] = "Devolução Etanol",
			                    'PCP-ACUMULADO'[VAR_CODIGO] = "0DEVPROCET"
			
			                )
			
			                    VAR IPM3 = 
			                        CALCULATE(
			                            [_m-R$MaiorMelhorIpm03],   
			                            'AREAS-APOIO'[PILAR] = "IPM - Indicador 03"
			                    )
			
			                        VAR IPM4 = 
			                            CALCULATE(
			                                [_m-R$MaiorMelhorIpm04],   
			                                'AREAS-APOIO'[PILAR] = "IPM - Indicador 04"
			                        )
			
			RETURN
			
			
			 APROV_IND +
			 DEV_ACUCAR +
			 DEV_ETANOL +
			 IPM3 +
			 IPM4
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 73ac8e7f-c8be-4ca6-9005-28baa4aff68c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure _m-AREAS-APOIO-INFRAESTRUTURA-PATIOS-UVT = ```
			
			
			
			VAR APROV_IND = 
			    CALCULATE(
			        [_m-R$MaiorMelhorPcpAreasApoio],     
			        'AREAS-APOIO'[PILAR] = "Aproveitamento de Tempo Industrial",
			        'PCP-ACUMULADO'[VAR_CODIGO] = "00APROVIND"
			    )
			
			
			    VAR IPM2 = 
			        CALCULATE(
			            [_m-R$MaiorMelhorIpm02],   
			            'AREAS-APOIO'[PILAR] = "IPM - Indicador 02"
			    )
			
			        VAR IPM3 = 
			            CALCULATE(
			                [_m-R$MaiorMelhorIpm03],   
			                'AREAS-APOIO'[PILAR] = "IPM - Indicador 03"
			        )
			
			            VAR IPM4 = 
			                CALCULATE(
			                    [_m-R$MaiorMelhorIpm04],   
			                    'AREAS-APOIO'[PILAR] = "IPM - Indicador 04"
			            )
			
			                VAR IPM5 = 
			                    CALCULATE(
			                        [_m-R$MaiorMelhorIpm05],   
			                        'AREAS-APOIO'[PILAR] = "IPM - Indicador 05"
			                )
			
			RETURN
			
			
			 APROV_IND +
			 IPM2 +
			 IPM3 +
			 IPM4 +
			 IPM5
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: efc152b2-3776-470a-9f82-268c37aba77e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure _m-AREAS-APOIO-LABORATORIO-IND-UVT = ```
			
			
			
			VAR APROV_IND = 
			    CALCULATE(
			        [_m-R$MaiorMelhorPcpAreasApoio],     
			        'AREAS-APOIO'[PILAR] = "Aproveitamento de Tempo Industrial",
			        'PCP-ACUMULADO'[VAR_CODIGO] = "00APROVIND"
			    )
			
			        VAR DEV_ACUCAR = 
			            CALCULATE(
			                [_m-R$MenorMelhorPcpAreasApoio],      
			                'AREAS-APOIO'[PILAR] = "Devolução de Açúcar",
			                'PCP-ACUMULADO'[VAR_CODIGO] = "0DEVPROCAC"
			            )
			
			                VAR DEV_ETANOL = 
			                    CALCULATE(
			                    [_m-R$MenorMelhorPcpAreasApoio],      
			                    'AREAS-APOIO'[PILAR] = "Devolução Etanol",
			                    'PCP-ACUMULADO'[VAR_CODIGO] = "0DEVPROCET"
			
			                )
			
			                    VAR TESTE_ACUCAR = 
			                        CALCULATE(
			                            [_m-R$AnalisesInterlaboratoriaisAreasApoio],   
			                            'AREAS-APOIO'[PILAR] = "Testes Interlaboratoriais Açúcar",
						                'PCP-ACUMULADO'[VAR_CODIGO] = "00INTERLAB"
			                    )
			
			                        VAR TESTE_ETANOL = 
			                            CALCULATE(
			                                [_m-R$AnalisesInterlaboratoriaisAreasApoio],   
			                                'AREAS-APOIO'[PILAR] = "Testes Interlaboratoriais Etanol",
							                'PCP-ACUMULADO'[VAR_CODIGO] = "00INTERLAB"
			                        )
			
			RETURN
			
			 APROV_IND +
			 DEV_ACUCAR +
			 DEV_ETANOL +
			 TESTE_ACUCAR +
			 TESTE_ETANOL
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 11068614-f7f6-46ee-8f69-5a0e166e81e9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure _m-AREAS-APOIO-PCM = ```
			
			
			
			VAR APROV_IND = 
			    CALCULATE(
			        [_m-R$MaiorMelhorPcpAreasApoio],     
			        'AREAS-APOIO'[PILAR] = "Aproveitamento de Tempo Industrial",
			        'PCP-ACUMULADO'[VAR_CODIGO] = "00APROVIND"
			    )
			
			
			    VAR IPM2 = 
			        CALCULATE(
			            [_m-R$ValorEntre_A_&_B_AreasApoio],   
			            'AREAS-APOIO'[PILAR] = "Backlog de Execução"
			    )
			
			        VAR IPM3 = 
			            CALCULATE(
			                [_m-R$MaiorMelhorAreasApoio],   
			                'AREAS-APOIO'[PILAR] = "Aderência ao início de Execução de O.S Programada"
			        )
			
			            VAR IPM4 = 
			                CALCULATE(
			                    [_m-R$MenorMelhorAreasApoio],   
			                    'AREAS-APOIO'[PILAR] = "Índice Horas Realiz. Corretivas"
			            )
			
			                VAR IPM5 = 
			                    CALCULATE(
			                        [_m-R$MaiorMelhorAreasApoio],   
			                        'AREAS-APOIO'[PILAR] = "Horas Produtivas"
			                )
			
			RETURN
			
			 APROV_IND +
			 IPM2 +
			 IPM3 +
			 IPM4 +
			 IPM5
			
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: a48c2786-a9aa-4746-af2f-310f1c5b11e1

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure _m-IPM-FABRICA-ETANOL-UCP = ```
			
			
			
			VAR EFICFERM = 
			    CALCULATE(
			        [_m-R$MaiorMelhorPcpAcumulado],     
			        'AREAS-PRODUCAO'[Indicador] = "Eficiência Fermentação p/ Subprodutos",
			        'PCP-ACUMULADO'[VAR_CODIGO] = "00000EFCTC",
			        'AREAS-PRODUCAO'[Pilar] = "IPM"
			    )
			
			    VAR EFICDEST = 
			        CALCULATE(
			            [_m-R$MaiorMelhorPcpAcumulado],      
			            'AREAS-PRODUCAO'[Indicador] = "Eficiência Destilação",
			            'AREAS-PRODUCAO'[Pilar] = "IPM",
			            'PCP-ACUMULADO'[VAR_CODIGO] = "00RENDDEST"
			        )
			
			        VAR PH = 
			            CALCULATE(
			                [_m-R$ValorEntre_A_&_B_ProlancaXxx],
			                'AREAS-PRODUCAO'[Pilar] = "IPM",
			                'AREAS-PRODUCAO'[Indicador]= "Controle de pH (Etanol Hidratado)",
			                'PCP-PROLANCA'[VAR_CODIGO]="0PRODALCPH",
			                'PCP-PROLANCA'[LAN_HORA] = "XXXX",
			                'PCP-PROLANCA'[SUF_CODIGO]="01",
			                'PCP-PROLANCA'[100 SafraProlanca] = "2025/2026"
			            )
			
			            VAR ACIDO = 
			                CALCULATE(
			                    'AREAS-PRODUCAO'[_m-R$MenorMelhor],
			                    'AREAS-PRODUCAO'[Indicador] = "Consumo de Ácido Sulfúrico",
			                    'AREAS-PRODUCAO'[Pilar] = "IPM"
			            )
			
			RETURN
			
			EFICFERM +
			EFICDEST +
			PH +
			ACIDO 
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: b176e276-86f0-47ee-a19b-74c313a32f3b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Column
		formatString: 0
		lineageTag: 940377dd-a3d1-4e48-b672-1ed027cc23c7
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition SOMA-TOTAL-PILAR-IPM = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 161c10b7368248938a81ca13ed178f7b

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

